services:
  frontend:
    build:
      context: frontend
    ports:
      - "8081:80"          # nginx внатре слуша 80, не 3000 dev сервер
    depends_on:
      - backend
    networks:
      - kii-net
    restart: unless-stopped

  backend:
    build:
      context: backend
    environment:
      MYSQL_HOST: db
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kii-net
      - db-net
    restart: unless-stopped

  db:
    image: mariadb:11.4
    environment:
      MYSQL_DATABASE: kii_app_db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db-net
    restart: unless-stopped

volumes:
  db-data: {}

secrets:
  db-password:
    file: ./db/password.txt

networks:
  kii-net: {}
  db-net: {}